---
title: "Data import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset. 

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


## Take a look at the data. 

Printing in the console 

```{r}
litters_df
```

```{r}
head(litters_df)
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

?read_csv

## Options to read CSV

```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

## Make r recognize missing values 

```{r}
litters_df = read_csv("./data/FAS_litters.csv", na = c("", "NA", ".", 999 ))

```

## Other file formats 

Read an excel file 

```{r}
mlb_df = read_excel("./data/mlb11.xlsx")
mlb_df
```

Read in a SAS file 

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Exporting data 

Export the mlb subtable 

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv") 
```




